# Generated by Django 2.2.6 on 2021-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('cluster_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增列集群id')),
                ('app_id', models.IntegerField(default=0, verbose_name='业务ID')),
                (
                    'cluster_status',
                    models.IntegerField(
                        choices=[
                            (0, '已下线'),
                            (1, '部署中'),
                            (2, '部署异常'),
                            (3, '上线中'),
                            (4, '集群变更中'),
                            (5, '集群异常'),
                            (99, '未知状态'),
                        ],
                        default=99,
                        verbose_name='集群状态',
                    ),
                ),
                ('cluster_name', models.CharField(max_length=50, unique=True, verbose_name='集群名称')),
                ('cluster_version', models.CharField(max_length=10, verbose_name='集群版本')),
                ('hdfs_data_dir', models.CharField(max_length=128, verbose_name='datanode数据目录')),
                ('hdfs_repl_num', models.IntegerField(default=2, verbose_name='hdfs文件副本数')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='ssh远程端口号')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='集群创建时间')),
                ('create_user', models.CharField(default='system', max_length=256, verbose_name='集群创建者')),
            ],
            options={
                'verbose_name': 'Hadoop集群信息表',
                'verbose_name_plural': 'Hadoop集群信息表',
                'db_table': 't_hadoop_cluster_info',
            },
        ),
        migrations.CreateModel(
            name='HadoopTaskRecord',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增列进程id')),
                ('app_id', models.IntegerField(default=0, verbose_name='业务ID')),
                (
                    'pipeline_id',
                    models.CharField(db_index=True, default='sync', max_length=128, verbose_name='pipeline任务id'),
                ),
                ('cluster_name', models.CharField(default='', max_length=256, verbose_name='集群名称')),
                ('task_mode', models.IntegerField(default=1, verbose_name='任务模式')),
                (
                    'task_status',
                    models.IntegerField(
                        choices=[
                            (1, '未执行'),
                            (2, '正在执行'),
                            (3, '执行完成'),
                            (4, '执行失败'),
                            (5, '跳过'),
                            (6, '忽略错误'),
                            (7, '等待用户'),
                            (8, '手动结束'),
                            (9, '状态异常'),
                            (10, '步骤强制终止中'),
                            (11, '步骤强制终止成功'),
                            (12, '步骤强制终止失败'),
                        ],
                        default=1,
                        verbose_name='结果表任务状态',
                    ),
                ),
                (
                    'task_type',
                    models.IntegerField(
                        choices=[
                            (0, '其他'),
                            (1, 'hdfs集群部署'),
                            (2, 'yarn集群部署'),
                            (3, 'hdfs_yarn集群部署'),
                            (4, 'hdfs_datanode节点扩容'),
                            (5, 'hdfs_datanode节点缩容'),
                            (6, 'yarn_nodemanager节点扩容'),
                            (7, 'yarn_nodemanager节点缩容'),
                            (8, 'hdfs_datanode多磁盘扩容'),
                        ],
                        default=0,
                        verbose_name='任务类型',
                    ),
                ),
                ('task_result', models.TextField(default='', verbose_name='任务信息')),
                ('task_info', models.TextField(default='', verbose_name='任务参数')),
                ('alert_status', models.IntegerField(choices=[(0, '未告警'), (1, '已告警')], default=0, verbose_name='告警状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='任务创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间')),
            ],
            options={'verbose_name': '后台任务记录表', 'verbose_name_plural': '后台任务记录表', 'db_table': 't_hadoop_task_record',},
        ),
        migrations.CreateModel(
            name='ClusterDetail',
            fields=[
                ('process_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增列进程id')),
                ('cluster_id', models.IntegerField(default=0, verbose_name='关联的集群ID')),
                ('process_name', models.CharField(max_length=15, verbose_name='进程名称')),
                ('hadoop_group_name', models.CharField(max_length=15, verbose_name='hadoop生态组件')),
                ('process_ip', models.CharField(max_length=15, verbose_name='进程所在ip')),
                ('process_hostname', models.CharField(max_length=128, verbose_name='进程所在hostname')),
                (
                    'process_status',
                    models.IntegerField(
                        choices=[(0, '已运行'), (1, '已关闭'), (2, '待回收'), (99, '未知状态')], default=99, verbose_name='进程状态'
                    ),
                ),
                ('package_version', models.CharField(max_length=10, verbose_name='进程版本')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='进程加入时间')),
            ],
            options={
                'verbose_name': 'Hadoop集群进程信息',
                'verbose_name_plural': 'Hadoop集群进程信息',
                'db_table': 't_hadoop_cluster_detail',
                'unique_together': {('cluster_id', 'process_name', 'process_ip')},
            },
        ),
    ]
