# Generated by Django 2.2.6 on 2021-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='hadooptaskrecord', name='task_info',),
        migrations.RemoveField(model_name='hadooptaskrecord', name='task_result',),
        migrations.AddField(
            model_name='hadooptaskrecord',
            name='pipeline_tree',
            field=models.TextField(default='', verbose_name='pipeline_tree'),
        ),
    ]
