# Generated by Django 2.2.6 on 2021-04-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0002_auto_20210331_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='base_dir',
            field=models.CharField(default='/data/hadoop_env', max_length=128, verbose_name='集群安装目录'),
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='cluster_user',
            field=models.CharField(default='hadoop', max_length=16, verbose_name='集群启动用户'),
        ),
    ]
