# Generated by Django 2.2.6 on 2021-04-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0003_auto_20210404_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='hdfs_excludes',
            field=models.CharField(
                default='/data/hadoop_env/hadoop/etc/hadoop/excludes', max_length=128, verbose_name='集群安装目录'
            ),
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='hdfs_includes',
            field=models.CharField(
                default='/data/hadoop_env/hadoop/etc/hadoop/includes', max_length=128, verbose_name='集群安装目录'
            ),
        ),
    ]
