# Generated by Django 2.2.6 on 2021-04-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0004_auto_20210405_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='hdfs_excludes',
            field=models.CharField(
                default='/data/hadoop_env/hadoop/etc/hadoop/excludes', max_length=128, verbose_name='集群hdfs黑名单路径'
            ),
        ),
        migrations.AlterField(
            model_name='clusterinfo',
            name='hdfs_includes',
            field=models.CharField(
                default='/data/hadoop_env/hadoop/etc/hadoop/includes', max_length=128, verbose_name='集群hdfs白名单路径'
            ),
        ),
    ]
