# Generated by Django 2.2.6 on 2021-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0005_auto_20210406_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='add_type',
            field=models.IntegerField(choices=[(0, '平台录入'), (1, '平台新建')], default=1, verbose_name='集群创建方式'),
        ),
    ]
