# Generated by Django 2.2.6 on 2021-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0007_auto_20210408_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadooptaskrecord', name='cluster_id', field=models.IntegerField(default=0, verbose_name='集群ID'),
        ),
    ]
