# Generated by Django 2.2.6 on 2021-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0008_hadooptaskrecord_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(model_name='hadooptaskrecord', name='cluster_id',),
        migrations.AlterField(
            model_name='hadooptaskrecord',
            name='task_status',
            field=models.IntegerField(
                choices=[
                    (1, '未执行'),
                    (2, '正在执行'),
                    (3, '执行完成'),
                    (4, '执行失败'),
                    (5, '跳过'),
                    (6, '忽略错误'),
                    (7, '等待用户'),
                    (8, '任务撤销'),
                    (9, '状态异常'),
                    (10, '步骤强制终止中'),
                    (11, '步骤强制终止成功'),
                    (12, '步骤强制终止失败'),
                ],
                default=1,
                verbose_name='结果表任务状态',
            ),
        ),
    ]
