# Generated by Django 2.2.6 on 2021-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0011_auto_20210412_0146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='clusterdetail', unique_together={('process_name', 'process_ip')},),
    ]
