# Generated by Django 2.2.6 on 2021-05-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0012_auto_20210421_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HadoopTaskRecord',
        ),
    ]
