# Generated by Django 2.2.6 on 2021-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0013_delete_hadooptaskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterinfo',
            name='app',
            field=models.CharField(default='', max_length=100, verbose_name='业务'),
        ),
    ]
