# Generated by Django 2.2.6 on 2021-05-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop', '0014_clusterinfo_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetail',
            name='app_id',
            field=models.IntegerField(default=0, verbose_name='业务id'),
        ),
    ]
