# Generated by Django 2.2.6 on 2021-04-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='BackendTaskRecord',),
        migrations.DeleteModel(name='KafkaTaskInfo',),
    ]
