# Generated by Django 2.2.6 on 2021-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0003_auto_20210421_1143'),
    ]

    operations = [
        migrations.RemoveField(model_name='kafkabroker', name='zone',),
        migrations.AddField(
            model_name='kafkacluster',
            name='zk_port',
            field=models.IntegerField(default=2181, verbose_name='zookeeper集群访问端口'),
        ),
    ]
