# Generated by Django 2.2.6 on 2021-04-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0004_auto_20210421_1531'),
    ]

    operations = [
        migrations.RemoveField(model_name='kafkacluster', name='address',),
        migrations.RemoveField(model_name='kafkacluster', name='yun',),
        migrations.RemoveField(model_name='kafkacluster', name='zone',),
    ]
