# Generated by Django 2.2.6 on 2021-04-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0005_auto_20210421_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kafkabroker', options={'verbose_name': 'kafka集群broker信息', 'verbose_name_plural': 'kafka集群broker信息'},
        ),
        migrations.AlterModelOptions(
            name='kafkacluster', options={'verbose_name': 'kafka集群信息', 'verbose_name_plural': 'kafka集群信息'},
        ),
        migrations.AlterModelOptions(
            name='topic', options={'verbose_name': 'kafka集群topic信息', 'verbose_name_plural': 'kafka集群topic信息'},
        ),
        migrations.AlterModelTable(name='kafkabroker', table='t_kafka_broker_detail',),
        migrations.AlterModelTable(name='kafkacluster', table='t_kafka_cluster_info',),
        migrations.AlterModelTable(name='topic', table='t_kafka_topic_detail',),
    ]
