# Generated by Django 2.2.6 on 2021-04-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0008_auto_20210422_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='create_by',
            field=models.CharField(default='', max_length=50, verbose_name='topic创建人'),
        ),
    ]
