# Generated by Django 2.2.6 on 2021-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0009_topic_create_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafkabroker',
            name='app',
        ),
        migrations.RemoveField(
            model_name='kafkabroker',
            name='broker_id',
        ),
        migrations.AddField(
            model_name='kafkabroker',
            name='app_id',
            field=models.IntegerField(default=0, verbose_name='业务id'),
        ),
    ]
