# Generated by Django 2.2.6 on 2021-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0010_auto_20210507_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='app',
        ),
        migrations.AlterField(
            model_name='kafkacluster',
            name='app_id',
            field=models.IntegerField(default=0, verbose_name='业务id'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cluster_name',
            field=models.CharField(default='', max_length=50, verbose_name='所属集群'),
        ),
        migrations.AlterIndexTogether(
            name='kafkacluster',
            index_together={('app_id', 'create_time')},
        ),
    ]
