# Generated by Django 2.2.6 on 2021-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0013_auto_20210705_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkacluster',
            name='bk_group_id',
            field=models.IntegerField(default=0, verbose_name='监控平台对应group_id ,0代表尚未部署监控'),
        ),
    ]
