# Generated by Django 2.2.6 on 2021-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EsFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('struct', models.TextField(default=None)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
