# Generated by Django 2.2.6 on 2021-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增列进程id')),
                ('app_id', models.IntegerField(default=0, verbose_name='业务ID')),
                ('pipeline_id', models.CharField(db_index=True, default='sync', max_length=128, verbose_name='pipeline任务id')),
                ('db_type', models.IntegerField(choices=[(1, 'ES'), (2, 'Hadoop'), (3, 'Kafka')], default=0, verbose_name='组件类型')),
                ('cluster_name', models.CharField(default='', max_length=256, verbose_name='集群名称')),
                ('task_mode', models.IntegerField(default=1, verbose_name='任务模式')),
                ('task_status', models.IntegerField(choices=[(1, '未执行'), (2, '正在执行'), (3, '执行完成'), (4, '执行失败'), (5, '任务暂停'), (6, '忽略错误'), (7, '等待用户'), (8, '任务撤销'), (9, '状态异常'), (10, '步骤强制终止中'), (11, '步骤强制终止成功'), (12, '步骤强制终止失败')], default=1, verbose_name='结果表任务状态')),
                ('task_type', models.IntegerField(choices=[(0, '其他'), (1, 'hdfs集群部署'), (2, 'yarn集群部署'), (3, '集群部署'), (4, 'datanode节点扩容'), (5, 'datanode节点缩容'), (6, 'nodemanager节点扩容'), (7, 'nodemanager节点缩容'), (8, '多磁盘扩容'), (9, '集群录入检测'), (10, '集群扩容'), (11, '集群缩容')], default=0, verbose_name='任务类型')),
                ('op_user', models.CharField(default='unknown', max_length=32, verbose_name='操作者')),
                ('task_kwargs', models.TextField(default='', verbose_name='任务参数')),
                ('pipeline_tree', models.TextField(default='', verbose_name='pipeline_tree')),
                ('alert_status', models.IntegerField(choices=[(0, '未告警'), (1, '已告警')], default=0, verbose_name='告警状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='任务创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间')),
                ('stop_time', models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间')),
            ],
            options={
                'verbose_name': '后台任务记录表',
                'verbose_name_plural': '后台任务记录表',
                'db_table': 't_task_record',
            },
        ),
    ]
