# Generated by Django 2.2.6 on 2021-05-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalview', '0003_auto_20210508_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EsFlow',
        ),
    ]
