# Generated by Django 2.2.6 on 2021-04-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0002_auto_20210324_0045'),
    ]

    operations = [
        migrations.DeleteModel(name='BackendTaskRecord',),
        migrations.DeleteModel(name='EsFlow',),
        migrations.DeleteModel(name='EsTaskInfo',),
    ]
