# Generated by Django 2.2.6 on 2021-04-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0003_auto_20210402_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='escluster',
            name='add_type',
            field=models.IntegerField(choices=[(0, '平台录入'), (1, '平台新建')], default=1, verbose_name='集群创建方式'),
        ),
    ]
