# Generated by Django 2.2.6 on 2021-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0004_escluster_add_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='escluster',
            name='cluster_status',
            field=models.IntegerField(
                choices=[
                    (0, '已下线'),
                    (1, '部署中'),
                    (2, '部署异常'),
                    (3, '上线中'),
                    (4, '集群变更中'),
                    (5, '集群异常'),
                    (6, '集群录入中'),
                    (7, '集群录入异常'),
                    (99, '未知状态'),
                ],
                default=3,
                verbose_name='集群状态',
            ),
        ),
    ]
