# Generated by Django 2.2.6 on 2021-04-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0005_escluster_cluster_status'),
    ]

    operations = [
        migrations.RemoveField(model_name='escluster', name='yun',),
        migrations.RemoveField(model_name='escluster', name='zone',),
        migrations.RemoveField(model_name='esnodeinfo', name='zone',),
    ]
