# Generated by Django 2.2.6 on 2021-04-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0007_auto_20210421_2046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='esnodeinfo', unique_together={('cluster_name', 'node_name', 'ip')},),
    ]
